sudo: required
services:
  - docker

before_install:
  - docker build -t kurabi/learntravisci -f Dockerfile.dev .

script:
  - docker run kurabi/learntravisci npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learntravisci"
  env: "Learntravisci-env"
  bucket_name: "elasticbeanstalk-us-east-2-628639610162"
  bucket_path: "learntravisci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
